/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'felipe' at '1/6/17 2:31 PM' with Gradle 2.10
 *
 * @author felipe, @date 1/6/17 2:31 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
